{% set name = "libpressio" %}
{% set version = "0.60.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/robertu94/libpressio/archive/{{ version }}.tar.gz
  sha256: a57fce96d50a603075a8a4a583431a1a03170df4d2894ff30f84d8c5ab4caf47

build:
  skip: True  # [win or osx]
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - python
    - sz
    - swig >=4.0.0
    - numpy
    - hdf5
    - stdcompat
  run:
    - python
    - sz
    - swig >=4.0.0
    - numpy
    - hdf5
    - stdcompat
    - numcodecs

about:
  home: https://robertu94.github.io/libpressio
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT.txt
  summary: 'Library to abstract between compressors and their configurations'
  description: |
    pressio is latin for compression. LibPressio is a C++ library with
    C compatible bindings to abstract between different lossless and
    lossy compressors and their configurations. It solves the problem
    of having to having to write separate application level code for
    each lossy compressor that is developed. Instead, users write
    application level code using LibPressio, and the library will make
    the correct underlying calls to the compressors. It provides
    interfaces to represent data, compressors settings, and compressors.
  doc_url: https://robertu94.github.io/libpressio
  dev_url: https://github.com/robertu94/libpressio

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
